// Code generated by MockGen. DO NOT EDIT.
// Source: imageservice/internal/app/image (interfaces: UseCase)

// Package mock is a generated GoMock package.
package mock

import (
	models "imageservice/internal/app/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// SetImage mocks base method.
func (m *MockUseCase) SetImage(arg0 models.UserImg) (models.UserImg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetImage", arg0)
	ret0, _ := ret[0].(models.UserImg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetImage indicates an expected call of SetImage.
func (mr *MockUseCaseMockRecorder) SetImage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetImage", reflect.TypeOf((*MockUseCase)(nil).SetImage), arg0)
}
