// Code generated by MockGen. DO NOT EDIT.
// Source: FL_2/store (interfaces: ResponseOrderRepository)

// Package mock is a generated GoMock package.
package mock

import (
	model "FL_2/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockResponseOrderRepository is a mock of ResponseOrderRepository interface.
type MockResponseOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockResponseOrderRepositoryMockRecorder
}

// MockResponseOrderRepositoryMockRecorder is the mock recorder for MockResponseOrderRepository.
type MockResponseOrderRepositoryMockRecorder struct {
	mock *MockResponseOrderRepository
}

// NewMockResponseOrderRepository creates a new mock instance.
func NewMockResponseOrderRepository(ctrl *gomock.Controller) *MockResponseOrderRepository {
	mock := &MockResponseOrderRepository{ctrl: ctrl}
	mock.recorder = &MockResponseOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseOrderRepository) EXPECT() *MockResponseOrderRepositoryMockRecorder {
	return m.recorder
}

// Change mocks base method.
func (m *MockResponseOrderRepository) Change(arg0 model.ResponseOrder) (*model.ResponseOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Change", arg0)
	ret0, _ := ret[0].(*model.ResponseOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Change indicates an expected call of Change.
func (mr *MockResponseOrderRepositoryMockRecorder) Change(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Change", reflect.TypeOf((*MockResponseOrderRepository)(nil).Change), arg0)
}

// Create mocks base method.
func (m *MockResponseOrderRepository) Create(arg0 model.ResponseOrder) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockResponseOrderRepositoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockResponseOrderRepository)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockResponseOrderRepository) Delete(arg0 model.ResponseOrder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockResponseOrderRepositoryMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockResponseOrderRepository)(nil).Delete), arg0)
}

// FindByOrderID mocks base method.
func (m *MockResponseOrderRepository) FindByOrderID(arg0 uint64) ([]model.ResponseOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrderID", arg0)
	ret0, _ := ret[0].([]model.ResponseOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrderID indicates an expected call of FindByOrderID.
func (mr *MockResponseOrderRepositoryMockRecorder) FindByOrderID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrderID", reflect.TypeOf((*MockResponseOrderRepository)(nil).FindByOrderID), arg0)
}
