// Code generated by MockGen. DO NOT EDIT.
// Source: authorizationservice/internal/app/profile (interfaces: UseCase)

// Package mock is a generated GoMock package.
package mock

import (
	models "authorizationservice/internal/app/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// Authentication mocks base method.
func (m *MockUseCase) Authentication(arg0, arg1 string, arg2 context.Context) (*models.UserBasicInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authentication", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.UserBasicInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authentication indicates an expected call of Authentication.
func (mr *MockUseCaseMockRecorder) Authentication(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authentication", reflect.TypeOf((*MockUseCase)(nil).Authentication), arg0, arg1, arg2)
}

// Create mocks base method.
func (m *MockUseCase) Create(arg0 models.NewUser, arg1 context.Context) (*models.UserBasicInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*models.UserBasicInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUseCaseMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUseCase)(nil).Create), arg0, arg1)
}
