// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson80a4d695DecodePostInternalAppModels(in *jlexer.Lexer, out *VacancySearch) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "keyword":
			out.Keyword = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson80a4d695EncodePostInternalAppModels(out *jwriter.Writer, in VacancySearch) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"keyword\":"
		out.RawString(prefix[1:])
		out.String(string(in.Keyword))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VacancySearch) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson80a4d695EncodePostInternalAppModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VacancySearch) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson80a4d695EncodePostInternalAppModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VacancySearch) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson80a4d695DecodePostInternalAppModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VacancySearch) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson80a4d695DecodePostInternalAppModels(l, v)
}
func easyjson80a4d695DecodePostInternalAppModels1(in *jlexer.Lexer, out *VacancyList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(VacancyList, 0, 0)
			} else {
				*out = VacancyList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Vacancy
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson80a4d695EncodePostInternalAppModels1(out *jwriter.Writer, in VacancyList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v VacancyList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson80a4d695EncodePostInternalAppModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VacancyList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson80a4d695EncodePostInternalAppModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VacancyList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson80a4d695DecodePostInternalAppModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VacancyList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson80a4d695DecodePostInternalAppModels1(l, v)
}
func easyjson80a4d695DecodePostInternalAppModels2(in *jlexer.Lexer, out *Vacancy) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint64(in.Uint64())
		case "customer_id":
			out.CustomerID = uint64(in.Uint64())
		case "executor_id":
			out.ExecutorID = uint64(in.Uint64())
		case "category":
			out.Category = string(in.String())
		case "vacancy_name":
			out.VacancyName = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "salary":
			out.Salary = uint64(in.Uint64())
		case "user_login":
			out.Login = string(in.String())
		case "user_img":
			out.Img = string(in.String())
		case "is_archived":
			out.IsArchived = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson80a4d695EncodePostInternalAppModels2(out *jwriter.Writer, in Vacancy) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ID))
	}
	if in.CustomerID != 0 {
		const prefix string = ",\"customer_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint64(uint64(in.CustomerID))
	}
	if in.ExecutorID != 0 {
		const prefix string = ",\"executor_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint64(uint64(in.ExecutorID))
	}
	if in.Category != "" {
		const prefix string = ",\"category\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Category))
	}
	if in.VacancyName != "" {
		const prefix string = ",\"vacancy_name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.VacancyName))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Description))
	}
	if in.Salary != 0 {
		const prefix string = ",\"salary\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint64(uint64(in.Salary))
	}
	if in.Login != "" {
		const prefix string = ",\"user_login\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Login))
	}
	if in.Img != "" {
		const prefix string = ",\"user_img\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Img))
	}
	{
		const prefix string = ",\"is_archived\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.IsArchived))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Vacancy) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson80a4d695EncodePostInternalAppModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Vacancy) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson80a4d695EncodePostInternalAppModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Vacancy) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson80a4d695DecodePostInternalAppModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Vacancy) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson80a4d695DecodePostInternalAppModels2(l, v)
}
func easyjson80a4d695DecodePostInternalAppModels3(in *jlexer.Lexer, out *SuggestVacancyTittleList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(SuggestVacancyTittleList, 0, 4)
			} else {
				*out = SuggestVacancyTittleList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v4 SuggestVacancyTittle
			(v4).UnmarshalEasyJSON(in)
			*out = append(*out, v4)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson80a4d695EncodePostInternalAppModels3(out *jwriter.Writer, in SuggestVacancyTittleList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v5, v6 := range in {
			if v5 > 0 {
				out.RawByte(',')
			}
			(v6).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v SuggestVacancyTittleList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson80a4d695EncodePostInternalAppModels3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SuggestVacancyTittleList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson80a4d695EncodePostInternalAppModels3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SuggestVacancyTittleList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson80a4d695DecodePostInternalAppModels3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SuggestVacancyTittleList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson80a4d695DecodePostInternalAppModels3(l, v)
}
func easyjson80a4d695DecodePostInternalAppModels4(in *jlexer.Lexer, out *SuggestVacancyTittle) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "title":
			out.Title = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson80a4d695EncodePostInternalAppModels4(out *jwriter.Writer, in SuggestVacancyTittle) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SuggestVacancyTittle) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson80a4d695EncodePostInternalAppModels4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SuggestVacancyTittle) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson80a4d695EncodePostInternalAppModels4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SuggestVacancyTittle) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson80a4d695DecodePostInternalAppModels4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SuggestVacancyTittle) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson80a4d695DecodePostInternalAppModels4(l, v)
}
